bb.edn, resources/templates/base.html, src/quickblog/api.clj, src/quickblog/internal.clj
- Renames `:categories` to `:tags`
- Creates `tags/index.html` and `tags/tag1.html` ... `tags/tagN.html`
=> Add tags pages

.gitignore, resources/templates/post.html, src/quickblog/api.clj
Extract post template to a file to avoid duplicating it in Selmer and Hiccup format
**Merge after [#4](https://github.com/borkdude/quickblog/pull/4)**
=> Post templates

src/quickblog/api.clj
=> Re-render index when contained posts have been modified

.gitignore, CHANGELOG.md, README.md, bb.edn, src/quickblog/api.clj, src/quickblog/internal.clj
=> Move metadata

CHANGELOG.md, README.md, bb.edn, src/quickblog/api.clj, src/quickblog/internal.clj, test/quickblog/api_test.clj
=> Add refresh-templates task

CHANGELOG.md, README.md, resources/quickblog/templates/base.html, src/quickblog/api.clj, src/quickblog/internal.clj, test/quickblog/api_test.clj
=> Improvements to social sharing

src/quickblog/api.clj, test/quickblog/api_test.clj
=> Fix bug where only modified clojure posts added to clojure feed

src/quickblog/cli.clj
#40 
Not really a feature, so I didn't think it was appropriate for the changelog
=> `bb quickblog serve` runs until interrupted

src/quickblog/api.clj, src/quickblog/cli.clj, src/quickblog/internal.clj
#37 
#38 
N/A because this is a bugfix
=> New blog exceptions

src/quickblog/api.clj
=> Fix bug in specifying tags for bb quickblog new

CHANGELOG.md, resources/quickblog/templates/base.html, resources/quickblog/templates/style.css
This aims to fix https://github.com/borkdude/quickblog/issues/48
=> Improve experience on mobile devices

src/quickblog/api.clj, src/quickblog/internal.clj, test/quickblog/api_test.clj
=> Disable flaky tests

CHANGELOG.md, src/quickblog/api.clj, src/quickblog/cli.clj
~~I don't think this PR requires a corresponding issue or an entry in the changelog. Just let me know if you disagree.~~
=> Use function argument to block while serving

CHANGELOG.md, src/quickblog/internal.clj
=> Make metadata available for use in templates

README.md
Says to create a PR to add your blog [here](https://github.com/borkdude/quickblog/blob/main/README.md)
Thx for the cool software!
=> Added my blog to instances of quickblog.

CHANGELOG.md, src/quickblog/internal.clj
#66 for reference
I'd have added tests, but the relevant areas of test suite seem to be having issues and are commented out.
=> Absolute post ordering

README.md
=> Update README.md - add a new instance of quickblog!

CHANGELOG.md, src/quickblog/api.clj, src/quickblog/internal.clj, test/quickblog/api_test.clj
=> Omit preview from index

CHANGELOG.md, src/quickblog/api.clj, src/quickblog/internal.clj, test/quickblog/api_test.clj
=> Remove livejs script tag on render

CHANGELOG.md, src/quickblog/api.clj
Probably not the neatest way to handle this so I'm open to suggestion :smile:
-------
=> feat: generate about.html if template exists

src/quickblog/internal.clj
Another one like #81, just adding another option from markdown-clj :smile:
-------
=> Add support for footnotes to markdown posts

CHANGELOG.md, README.md, src/quickblog/api.clj, test/quickblog/api_test.clj
=> Support Selmer template for new posts

README.md
This is just a small PR to request adding my programming blog to the list of example quickblog blogs. Feel free to ignore if you feel it's not a good fit! Thank you for this amazing project.
=> Update README.md to add Kira's programming blog to quickblog examples

.gitignore, CHANGELOG.md, deps.edn, src/quickblog/internal.clj
closes #96 
requires https://github.com/yogthos/markdown-clj/pull/200 to me merged in.
=> feat: add pre/clode language-xxx class to code blocks

README.md
=> docs: update README to add Ed's blog

deps.edn
=> Bump markdown-clj version to fix link target bug
